apply cwd for yt-dlp wrapper script to ensure having a proper permission
Releated: 76bffccf2e649efded5b6ab58feafe951bab9254

diff --git a/root/app/bin/yt-dlp b/root/app/bin/yt-dlp
--- a/root/app/bin/yt-dlp
+++ b/root/app/bin/yt-dlp
@@ -12,6 +12,8 @@ if ! flock -x -w 10 200; then
     exit 1
 fi
 
+cd /down || exit 1 # better run yt-dlp with --paths to be free from permission error
+
 s6-setuidgid abc /usr/local/bin/yt-dlp "$@"
 
 echo "[rsync] executing => rsync -a --remove-sources-files /down/ /downloads/"
